### ISSUE TITLE
Android: org.json.JSONException when trying to dowload

### ISSUE THREAD

**Issue by LogicalDash** [Fmstrat/ownnote#202]
I have ownCloud 8.0.4 installed at https://example.com/owncloud/

Notes app is enabled and works fine in the browser. I have a valid Comodo SSL cert.

When I ask MyOwnNotes to sync with this server, it complains that it doesn't receive valid JSON. This is what appears in the logcat:

```
D/NoteListActivity(28787): download connection ok, doing the downloading
W/System.err(28787): org.json.JSONException: Value <!DOCTYPE of type java.lang.String cannot be converted to JSONArray
W/System.err(28787):    at org.json.JSON.typeMismatch(JSON.java:111)
W/System.err(28787):    at org.json.JSONArray.<init>(JSONArray.java:96)
W/System.err(28787):    at org.json.JSONArray.<init>(JSONArray.java:108)
W/System.err(28787):    at org.aykit.owncloud_notes.NoteListActivity.updateDatabase(NoteListActivity.java:513)
W/System.err(28787):    at org.aykit.owncloud_notes.NoteListActivity$DownloadNotesTask.onPostExecute(NoteListActivity.java:1264)
W/System.err(28787):    at org.aykit.owncloud_notes.NoteListActivity$DownloadNotesTask.onPostExecute(NoteListActivity.java:1129)
W/System.err(28787):    at android.os.AsyncTask.finish(AsyncTask.java:632)
W/System.err(28787):    at android.os.AsyncTask.access$600(AsyncTask.java:177)
W/System.err(28787):    at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
W/System.err(28787):    at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err(28787):    at android.os.Looper.loop(Looper.java:135)
W/System.err(28787):    at android.app.ActivityThread.main(ActivityThread.java:5254)
W/System.err(28787):    at java.lang.reflect.Method.invoke(Native Method)
W/System.err(28787):    at java.lang.reflect.Method.invoke(Method.java:372)
W/System.err(28787):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
W/System.err(28787):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
E/NoteListActivity(28787): no correct JSON data returned from server. result from server:<!DOCTYPE html><!--[if lt IE 7]><html class="ng-csp ie ie6 lte9 lte8 lte7" data-placeholder-focus="false" lang="en"><![endif]--><!--[if IE 7]><html class="ng-csp ie ie7 lte9 lte8 lte7" data-placeholder-focus="false" lang="en" ><![endif]--><!--[if IE 8]><html class="ng-csp ie ie8 lte9 lte8" data-placeholder-focus="false" lang="en" ><![endif]--><!--[if IE 9]><html class="ng-csp ie ie9 lte9" data-placeholder-focus="false" lang="en" ><![endif]--><!--[if gt IE 9]><html class="ng-csp ie" data-placeholder-focus="false" lang="en" ><![endif]--><!--[if !IE]><!--><html class="ng-csp" data-placeholder-focus="false" lang="en" ><!--<![endif]-->        <head data-user="sanotehu" data-requesttoken="SntHu8e/Jb7csqrepOyazb/HgOLvXH">          <title>                 Files - ownCloud                </title>                <meta charset="utf-8">          <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />             <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0">            <meta name="apple-itunes-app" content="app-id=543672169">            <meta name="apple-mobile-web-app-capable" content="yes">                <meta name="apple-mobile-web-app-status-bar-style" content="black">             <meta name="apple-mobile-web-app-title" content="ownCloud">         <meta name="mobile-web-app-capable" content="yes">               <link rel="shortcut icon" type="image/png" href="/owncloud/core/img/favicon.png" />             <link rel="apple-touch-icon-precomposed" href="/owncloud/core/img/favicon-touch.png" />                                      <link rel="stylesheet" href="/owncloud/core/css/styles.css?v=4bb5d820ecc90794f0a113d5bb2d7a3f" type="text/css" media="screen" />                                        <link rel="stylesheet" href="/owncloud/core/css/header.css?v=4bb5d820ecc90794f0a113d5bb2d7a3f" type="text/css" media="screen" />                                     <link rel="stylesheet" href="/owncloud/core/css/mobile.css?v=4bb5d820ecc90794f0a113d5bb2d7a3f" type="text/css" media="screen" />                                     <link rel="stylesheet" href="/owncloud/core/css/icons.css?v=4bb5d820ecc90794f0a113d5bb2d7a3f" type="text/css" media="screen" />                                 <link rel="stylesheet" href="/owncloud/core/css/fonts.css?v=4bb5d820ecc90794f0a113d5bb2d7a3f" type="text/css" media="screen" />                                      <link rel="stylesheet" href="/owncloud/core/css/apps.css?v=4bb5d820ecc90794f0a113d5bb2d7a3f" type="text/css" media="screen" />                                       <link rel="stylesheet" href="/owncloud/core/css/fixes.css?v=4bb5d820ecc90794f0a113d5bb2d7a3f" type="text/css" media="screen" />                     <link rel="stylesheet" href="/owncloud/core/css/multiselect.css?v=4bb5d820ecc90794f0a113d5bb2d7a3f" type="text/css" media="screen" />                                    <link rel="stylesheet" href="/owncloud/core/vendor/jquery-ui/themes/base/jquery-ui.css?v=4bb5d820ecc90794f0a113d5bb2d7a3f" type="text/css" media="screen" />                                 <link rel="stylesheet" href="/owncloud/core/css/jquery-ui-fixes.css?v=4bb5d820ecc90794f0a113d5bb2d7a3f" type="text/css" media="screen" />                                    <link rel="stylesheet" href="/owncloud/core/css/jquery-tipsy.css?v=4bb5d820ecc90794f0a113d5bb2d7a3f" type="text/css" media="screen" />                                  <link rel="stylesheet" href="/owncloud/core/css/jquery.ocdialog.css?v=4bb5d820ecc90794f0a113d5bb2d7a3f" type="text/css" media="screen" />                                    <link rel="stylesheet" href="/owncloud/core/css/share.css?v=4bb5d820ecc90794f0a113d5bb2d7a3f" type="text/css" media="screen" />                                      <link rel="stylesheet" href="/owncloud/apps/files_versions/css/versions.css?v=4bb5d820ecc90794f0a113d5bb2d7a3f" type="text/css" media="screen" />   <link rel="stylesheet" href="/owncloud/apps/calendar/css/../3rdparty/chosen/css/chosen.css?v=4bb5d820ecc90794f0a113d5bb2d7a3f" type="text/css" media="screen" />                                 <link rel="stylesheet" href="/owncloud/apps/calendar/css/../3rdparty/miniColors/css/jquery.miniColors.css?v=4bb5d820ecc90794f0a113d5bb2d7a3f" type="text/css" media="screen" />                                      <link rel="stylesheet" href="/owncloud/apps/files_texteditor/css/DroidSansMono/stylesheet.css?v=4bb5d820ecc90794f0a113d5bb2d7a3f" type="text/css" media="screen" />                                  <link rel="stylesheet" href="/owncloud/apps/files_texteditor/css/style.css?v=4bb5d820ecc90794f0a113d5bb2d7a3f" type="te
D/NoteListActivity(28787): updateDatabase() executed
```

It appears that it tried to download the ownCloud front page and not the notes.

**Comment by Fmstrat** [comment]
What shows up in the owncloud.log?

**Comment by LogicalDash** [comment]
{"reqId":"b574d2bfe9dc72e53a2bfe82a53f488f","remoteAddr":"141.155.174.94","app":"PHP","message":"DateTimeZone::__construct(): Unknown or bad timezone (Eastern Standard Time) at \/var\/www\/owncloud\/3rdparty\/sabre\/vobject\/lib\/Sabre\/VObject\/TimeZoneUtil.php#412","level":3,"time":"2015-07-16T11:25:32+00:00"}
{"reqId":"a245b341e9d24db9dd76b85ba3d5c935","remoteAddr":"","app":"PHP","message":"Undefined index: REQUEST_URI at \/var\/www\/owncloud\/apps\/calendar\/appinfo\/app.php#41","level":3,"time":"2015-07-16T12:00:01+00:00"}

**Comment by Fmstrat** [comment]
Ohhh, you're using the old original notes app, not ownNote. :)

ownNote can be found here for the server: https://apps.owncloud.com/content/show.php/ownNote+-+Notes+Application?content=168512 (or in the "App Store" in ownCloud)

And for Android here: https://play.google.com/store/apps/details?id=com.nowsci.ownnote

If you need support for the original text-only Notes app, you'll have to go to the MyOwnNote repository. Thanks!

**Comment by LogicalDash** [comment]
OK, you might want to see about replacing MyOwnNotes in [FDroid](http://fdroid.org/) with the new ownNote app, or at least putting a note in the old app's description.

**Comment by Fmstrat** [comment]
Unfortunately I don't manage the original Notes app, so I'm unable to do that. Thanks for the feedback, though.
