### ISSUE TITLE
Can't enable ownNote

### ISSUE THREAD

**Issue by andyforceno** [Fmstrat/ownnote#345]
When I enable ownNote, it immediately disables. I'm seeing the following in owncloud.log (I'm running ownCloud 9.1).

```{"reqId":"jkAvP3CoDJUwolER8dM\/","remoteAddr":"192.168.1.5","app":"no app in context","message":"Exception: {\"Exception\":\"Symfony\\\\Component\\\\Routing\\\\Exception\\\\RouteNotFoundException\",\"Message\":\"Unable to generate a URL for the named route \\\"news.page.index\\\" as such route does not exist.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(320): Symfony\\\\Component\\\\Routing\\\\Generator\\\\UrlGenerator->generate('news.page.index', Array, 1)\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/URLGenerator.php(67): OC\\\\Route\\\\Router->generate('news.page.index', Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/apps\\\/news\\\/config\\\/appconfig.php(108): OC\\\\URLGenerator->linkToRoute('news.page.index')\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/NavigationManager.php(63): OCA\\\\News\\\\Config\\\\AppConfig->OCA\\\\News\\\\Config\\\\{closure}()\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/app.php(698): OC\\\\NavigationManager->getAll()\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/TemplateLayout.php(83): OC_App::getNavigation()\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/template.php(229): OC\\\\TemplateLayout->__construct('user', 'files')\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/public\\\/AppFramework\\\/Http\\\/TemplateResponse.php(156): OC_Template->fetchPage()\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(112): OCP\\\\AppFramework\\\\Http\\\\TemplateResponse->render()\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(99): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files\\\\Controller\\\\ViewController), 'index')\\n#10 {"reqId":"jkAvP3CoDJUwolER8dM\/","remoteAddr":"192.168.1.5","app":"no app in context","message":"Exception: {\"Exception\":\"Symfony\\\\Component\\\\Routing\\\\Exception\\\\RouteNotFoundException\",\"Message\":\"Unable to generate a URL for the named route \\\"news.page.index\\\" as such route does not exist.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(320): Symfony\\\\Component\\\\Routing\\\\Generator\\\\UrlGenerator->generate('news.page.index', Array, 1)\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/URLGenerator.php(67): OC\\\\Route\\\\Router->generate('news.page.index', Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/apps\\\/news\\\/config\\\/appconfig.php(108): OC\\\\URLGenerator->linkToRoute('news.page.index')\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/NavigationManager.php(63): OCA\\\\News\\\\Config\\\\AppConfig->OCA\\\\News\\\\Config\\\\{closure}()\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/app.php(698): OC\\\\NavigationManager->getAll()\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/TemplateLayout.php(83): OC_App::getNavigation()\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/template.php(229): OC\\\\TemplateLayout->__construct('user', 'files')\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/public\\\/AppFramework\\\/Http\\\/TemplateResponse.php(156): OC_Template->fetchPage()\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(112): OCP\\\\AppFramework\\\\Http\\\\TemplateResponse->render()\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(99): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files\\\\Controller\\\\ViewController), 'index')\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(46): OC\\\\AppFramework\\\\App::main('ViewController', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#11 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#12 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(280): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#13 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(891): OC\\\\Route\\\\Router->match('\\\/apps\\\/files')\\n#14 \\\/var\\\/www\\\/owncloud\\\/index.php(54): OC::handleRequest()\\n#15 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/symfony\\\/routing\\\/Generator\\\/UrlGenerator.php\",\"Line\":130}","level":3,"time":"2017-06-01T01:02:23+00:00","method":"GET","url":"\/owncloud\/apps\/files","user":"andy"}\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(46): OC\\\\AppFramework\\\\App::main('ViewController', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#11 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#12 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(280): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#13 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(891): OC\\\\Route\\\\Router->match('\\\/apps\\\/files')\\n#14 \\\/var\\\/www\\\/owncloud\\\/index.php(54): OC::handleRequest()\\n#15 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/symfony\\\/routing\\\/Generator\\\/UrlGenerator.php\",\"Line\":130}","level":3,"time":"2017-06-01T01:02:23+00:00","method":"GET","url":"\/owncloud\/apps\/files","user":"andy"}```

**Comment by andyforceno** [comment]
Oops, sorry. I posted this to the wrong place.
